{{- if (and .Values.falco.auditLog.enabled .Values.falco.auditLog.dynamicBackend.enabled) }}
apiVersion: auditregistration.k8s.io/v1alpha1
kind: AuditSink
metadata:
  name: {{ template "falco.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  policy:
    level: RequestResponse
    stages:
      - ResponseComplete
      - ResponseStarted
  webhook:
    throttle:
      qps: 10
      burst: 15
    clientConfig:
      {{- if .Values.falco.auditLog.dynamicBackend.url }}
      url: {{ .Values.falco.auditLog.dynamicBackend.url }}
      {{- else }}
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ template "falco.fullname" . }}
        port: {{ .Values.falco.falco.webserver.listenPort }}
        path: {{ .Values.falco.falco.webserver.k8sAuditEndpoint }}
      {{- end }}
      {{- if .Values.falco.falco.webserver.sslEnabled }}
      caBundle: {{ .Values.falco.certs.ca.crt | b64enc | quote }}
      {{- end}}
{{- end }}
