apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: falco-app
  repository: file://.
  version: 1.12.0
- name: falco-exporter
  repository: file://.
  version: 0.5.1
- name: falcosidekick
  repository: file://.
  version: 0.3.7
description: A Helm chart for falco
home: https://github.com/giantswarm/falco-app
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
name: falco-app
version: [[ .Version ]]
type: library
