apiVersion: v2
appVersion: [[ .Version ]]
annotations:
  application.giantswarm.io/team: "shield"
  config.giantswarm.io/version: 1.x.x
dependencies:
- name: falco
  version: 2.2.0
- name: falco-exporter
  version: 0.9.1
- name: falcosidekick
  version: 0.5.9
description: A Helm chart for falco
engine: gotpl
home: https://github.com/giantswarm/falco-app
icon: https://s.giantswarm.io/app-icons/falco/1/dark.svg
maintainers:
- name: Giant Swarm applications team
  url: https://github.com/giantswarm/falco-app
name: falco-app
sources:
- https://github.com/giantswarm/falco-app
version: [[ .Version ]]
