global:
  registry: quay.io

falco:
  podSecurityPolicy:
    create: true
  serviceAccount:
    name: falco-user

falco-exporter:
  podSecurityPolicy:
    create: true
  serviceAccount:
    name: falco-user
