global:
  registry: quay.io

falco:
  podSecurityPolicy:
    create: true
  serviceAccount:
    name: falco-user
  falco:
    grpc:
      enabled: true
    grpcOutput:
      enabled: true

falco-exporter:
  podSecurityPolicy:
    create: true
  serviceAccount:
    name: falco-user
