falco:
  image:
    registry: docker.io
    repository: giantswarm/falco
  podSecurityPolicy:
    create: true
  falco:
    grpc:
      enabled: true
    grpcOutput:
      enabled: true

falco-exporter:
  image:
    registry: docker.io
    repository: giantswarm/falco-exporter
  podSecurityPolicy:
    create: true
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

falcosidekick:
  image:
    registry: docker.io
    repository: giantswarm/falcosidekick
