version: 2.1
orbs:
  architect: giantswarm/architect@5.10.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: "architect"
          executor: "app-build-suite"
          name: push-falco-app-to-control-plane-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          persist_chart_archive: true
          chart: "falco"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: "architect"
          executor: "app-build-suite"
          name: push-falco-app-to-giantswarm-catalog
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          persist_chart_archive: true
          chart: "falco"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: aws-app-collection
          context: "architect"
          app_name: "falco"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-falco-app-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: azure-app-collection
          context: "architect"
          app_name: "falco"
          app_collection_repo: "azure-app-collection"
          requires:
            - push-falco-app-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      #- architect/push-to-app-collection:
      #    name: kvm-app-collection
      #    context: "architect"
      #    app_name: "falco"
      #    app_collection_repo: "kvm-app-collection"
      #    requires:
      #      - push-falco-app-to-control-plane-catalog
      #    filters:
      #      branches:
      #        ignore: /.*/
      #      tags:
      #        only: /^v.*/

      - architect/push-to-app-collection:
          name: vsphere-app-collection
          context: "architect"
          app_name: "falco"
          app_collection_repo: "vsphere-app-collection"
          requires:
            - push-falco-app-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-cloud-director-app-collection
          app_name: "falco"
          app_collection_repo: "cloud-director-app-collection"
          requires:
            - push-falco-app-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-capa-app-collection
          app_name: "falco"
          app_collection_repo: "capa-app-collection"
          requires:
            - push-falco-app-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-capz-app-collection
          app_name: "falco"
          app_collection_repo: "capz-app-collection"
          requires:
            - push-falco-app-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-gcp-app-collection
          app_name: "falco"
          app_collection_repo: "gcp-app-collection"
          requires:
            - push-falco-app-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
