{{- if .Values.rbac.create }}
kind: ClusterRole
apiVersion: {{ template "rbac.apiVersion" . }}
metadata:
  name: {{ template "falco-app.fullname" .}}
  labels:
    app: {{ template "falco-app.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
  - apiGroups:
      - extensions
      - ""
    resources:
      - nodes
      - namespaces
      - pods
      - replicationcontrollers
      - replicasets
      - services
      - daemonsets
      - deployments
      - events
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs:
      - /healthz
      - /healthz/*
    verbs:
      - get
{{- if .Values.podSecurityPolicy.create }}
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    resourceNames:
      - {{ template "falco-app.fullname" . }}
{{- if .Values.fakeEventGenerator.enabled }}
      - event-generator-{{ template "falco-app.fullname" . }}
{{- end }}
    verbs:
      - use
{{- end }}
{{- end }}
