{{- if .Values.customRules }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "falco-app.fullname" . }}-rules
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "falco-app.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
{{- range $file, $content :=  .Values.customRules }}
  {{ $file }}: |-
{{ $content | indent 4}}
{{- end }}
{{- end }}
