{{- if .Values.fakeEventGenerator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "falco-app.fullname" . }}-event-generator
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "falco-app.fullname" . }}-event-generator
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas:  {{ .Values.fakeEventGenerator.replicas }}
  selector:
    matchLabels:
      app: {{ template "falco-app.fullname" . }}-event-generator
  template:
    metadata:
      labels:
        app: {{ template "falco-app.fullname" . }}-event-generator
    spec:
      serviceAccountName: {{ template "falco-app.serviceAccountName" .}}
      containers:
      - name: {{ template "falco-app.fullname" . }}-event-generator
        securityContext:
            privileged: false
        image: falcosecurity/event-generator:latest
{{- with .Values.fakeEventGenerator.args }}
        args:
{{ toYaml . | indent 10 }}
{{- end }}
{{- end }}
