apiVersion: v1
appVersion: 0.0.1
description: A Helm chart for falco
engine: gotpl
home: https://github.com/giantswarm/falco-app
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
name: falco
sources:
- https://github.com/some-org/some-repo
version: [[ .Version ]]
