apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "falco-helpers.updateLogic" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-4"
    {{- include "falco-helpers.UpdateLogicAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "falco-helpers.updateLogic" . | quote }}
    {{- include "falco.selectorLabels" . | nindent 4 }}
    role: {{ include "falco-helpers.UpdateLogicSelector" . | quote }}
