ciliumNetworkPolicy:
  enabled: true

global:
  podSecurityStandards:
    enforced: true

verticalPodAutoscaler:
  enabled: false

kyvernoPolicyExceptions:
  enabled: true
  namespace: giantswarm

falco:
  enabled: true
  image:
    registry: gsoci.azurecr.io
    repository: giantswarm/falco
  priorityClassName: giantswarm-critical
  collectors:
    kubernetes:
      enabled: true
  driver:
    kind: modern_ebpf
    loader:
      initContainer:
        image:
          registry: gsoci.azurecr.io
          repository: giantswarm/falco-driver-loader
  customRules:
    gs-root-ca-key-access.yaml: |-
      - list: root_ca_key_path
        items:
        - "/etc/kubernetes/pki/ca.key"
      - rule: File Related Operation on Root CA Key Path
        desc: Detect any file operation on the path to root CA key
        condition: (fs.path.name pmatch (root_ca_key_path) or fs.path.source pmatch (root_ca_key_path) or fs.path.target pmatch (root_ca_key_path))
        output: "Root CA key file '%fs.path.name' was accessed via operation '%evt.type' (source path '%fs.path.source', target path '%fs.path.target') triggered by the user '%user.name' running '%proc.cmdline' (from '%proc.pcmdline') in container '%container.name' (ID=%container.id) built from image '%container.image.repository'. Additional details (if available):"
        priority: WARNING
        source: syscall
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
  # ebpf:
  #   enabled: true
  controller:
    labels:
      application.giantswarm.io/team: "shield"
  falco:
    grpc:
      enabled: true
    grpc_output:
      enabled: true
  serviceAccount:
    # We set the service account name only so that we can use it for attaching a PSP.
    name: "falco"
  falcoctl:
    image:
      registry: gsoci.azurecr.io
      repository: giantswarm/falcoctl
  tty: true
  k8s-metacollector:
    fullnameOverride: ""
    service:
      ports:
        broker-grpc:
          port: 45000

falcosidekick:
  enabled: true
  image:
    registry: gsoci.azurecr.io
    repository: giantswarm/falcosidekick

k8s-metacollector:
  enabled: true
  image:
    registry: gsoci.azurecr.io
    repository: giantswarm/k8s-metacollector
