ciliumNetworkPolicy:
  enabled: false

global:
  podSecurityStandards:
    enforced: false

verticalPodAutoscaler:
  enabled: false

kyvernoPolicyExceptions:
  enabled: true
  namespace: giantswarm

falco:
  image:
    registry: docker.io
    repository: giantswarm/falco-no-driver
  priorityClassName: giantswarm-critical
  driver:
    kind: ebpf
    loader:
      initContainer:
        image:
          registry: docker.io
          repository: giantswarm/falco-driver-loader
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
  # ebpf:
  #   enabled: true
  falco:
    grpc:
      enabled: true
    grpc_output:
      enabled: true
  serviceAccount:
    # We set the service account name only so that we can use it for attaching a PSP.
    name: "falco"
    rules_file:
      - /etc/falco/falco_rules.yaml
      - /etc/falco/falco_rules.local.yaml
      - /etc/falco/falco-incubating_rules.yaml
      - /etc/falco/falco-sandbox_rules.yaml
      - /etc/falco/rules.d
  falcoctl:
    image:
      registry: docker.io
      repository: giantswarm/falcoctl
    config:
      artifact:
        install:
          refs: [falco-rules:2, falco-incubating-rules:2, falco-sandbox-rules:2]
        follow:
          refs: [falco-rules:2, falco-incubating-rules:2, falco-sandbox-rules:2]

falco-exporter:
  image:
    registry: docker.io
    repository: giantswarm/falco-exporter
  podSecurityPolicy:
    create: true
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane

falcosidekick:
  image:
    registry: docker.io
    repository: giantswarm/falcosidekick
