ciliumNetworkPolicy:
  enabled: true

global:
  podSecurityStandards:
    enforced: false

verticalPodAutoscaler:
  enabled: false

kyvernoPolicyExceptions:
  enabled: true
  namespace: giantswarm

falco:
  image:
    registry: gsoci.azurecr.io
    repository: giantswarm/falco-no-driver
  priorityClassName: giantswarm-critical
  driver:
    kind: ebpf
    loader:
      initContainer:
        image:
          registry: gsoci.azurecr.io
          repository: giantswarm/falco-driver-loader
  customRules:
    gs-root-ca-key-access.yaml: |-
      - list: root_ca_key_path
        items:
        - "/etc/kubernetes/pki/ca.key"
      - rule: File Related Operation on Root CA Key Path
        desc: Detect any file operation on the path to root CA key
        condition: (fs.path.name pmatch (root_ca_key_path) or fs.path.source pmatch (root_ca_key_path) or fs.path.target pmatch (root_ca_key_path))
        output: "Some File Related Operation on root CA key (evt.type=%evt.type path=%fs.path.name source=%fs.path.source target=%fs.path.target user.name=%user.name proc.cmdline=%proc.cmdline proc.pcmdline=%proc.pcmdline container.id=%container.id container.name=%container.name image=%container.image.repository)"
        priority: WARNING
        source: syscall
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
  # ebpf:
  #   enabled: true
  falco:
    grpc:
      enabled: true
    grpc_output:
      enabled: true
  serviceAccount:
    # We set the service account name only so that we can use it for attaching a PSP.
    name: "falco"
  falcoctl:
    image:
      registry: gsoci.azurecr.io
      repository: giantswarm/falcoctl
  tty: true

falco-exporter:
  image:
    registry: gsoci.azurecr.io
    repository: giantswarm/falco-exporter
  podSecurityPolicy:
    create: true
    annotations: {seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'}
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane

falcosidekick:
  image:
    registry: gsoci.azurecr.io
    repository: giantswarm/falcosidekick
