ciliumNetworkPolicy:
  enabled: true

global:
  podSecurityStandards:
    enforced: false

verticalPodAutoscaler:
  enabled: false

kyvernoPolicyExceptions:
  enabled: true
  namespace: giantswarm

falco:
  image:
    registry: gsoci.azurecr.io
    repository: giantswarm/falco-no-driver
  priorityClassName: giantswarm-critical
  driver:
    kind: ebpf
    loader:
      initContainer:
        image:
          registry: gsoci.azurecr.io
          repository: giantswarm/falco-driver-loader
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
  # ebpf:
  #   enabled: true
  falco:
    grpc:
      enabled: true
    grpc_output:
      enabled: true
  serviceAccount:
    # We set the service account name only so that we can use it for attaching a PSP.
    name: "falco"
  falcoctl:
    image:
      registry: gsoci.azurecr.io
      repository: giantswarm/falcoctl

falco-exporter:
  image:
    registry: gsoci.azurecr.io
    repository: giantswarm/falco-exporter
  podSecurityPolicy:
    create: true
    annotations: {seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'}
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  serviceMonitor:
    additionalLabels:
      application.giantswarm.io/team: "shield"
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane

falcosidekick:
  image:
    registry: gsoci.azurecr.io
    repository: giantswarm/falcosidekick
