  apiVersion: kyverno.io/v2alpha1
  kind: PolicyException
  metadata:
    name: {{ include "falco-helpers.fullname" . }}-disallow-host-path-exception
    namespace: {{ include "falco-helpers.namespace" . }}
  spec:
    exceptions:
    - policyName: disallow-host-path
      ruleNames:
      - host-path
    match:
      any:
      - resources:
          kinds:
          - DaemonSet
          - Deployment
          namespaces:
          - {{ include "falco-helpers.namespace" . }}
          names:
          - falco*
          - falco-falco-exporter*
          - falco-falcosidekick*
