{{- if .Values.ciliumNetworkPolicy.enabled }}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "falco-helpers.fullname" . }}
  namespace: {{ include "falco-helpers.namespace" . }}
  labels:
    {{- include "falco-helpers.labels" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      {{- include "falco.selectorLabels" . | nindent 6 }}
  egress:
    - toEntities:
        - kube-apiserver
        - world
    - toEntities:
        - cluster
      toPorts:
        - ports:
            - port: "1053"
            - port: "53"
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/instance: {{ include "falco-helpers.fullname" . }}
            app.kubernetes.io/name: falcosidekick
      toPorts:
        - ports:
            - port: "2801"
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/instance: {{ include "falco-helpers.fullname" . }}
            app.kubernetes.io/name: k8s-metacollector
      toPorts:
        - ports:
            - port: "45000"
  ingress:
    - fromEntities:
        - kube-apiserver
        - cluster
{{- end }}